name: Deploy

on:
  push
  # push:
  #   branches:
  #     - "main"
  #   tags:
  #     - "[0-9]+.[0-9]+.[0-9]+"

# permissions:
#   contents: write

jobs:
  build-and-upload:
    name: Build and upload
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - build: linux
            os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - build: linux
            os: ubuntu-latest
            target: x86_64-unknown-linux-musl
          - build: macos
            os: macos-latest
            target: x86_64-apple-darwin
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get the release version from the tag
        shell: bash
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" | tee --append $GITHUB_ENV
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}
      - name: Build
        run: cargo build --release --target ${{ matrix.target }}
      - name: Create archive
        shell: bash
        run: |
          binary_name="pandoras_pot"
          dirname="$binary_name-${{ env.VERSION }}-${{ matrix.target }}"
          mkdir "$dirname"
          mv "target/${{ matrix.target }}/release/$binary_name" "$dirname"
          result="$dirname.tar.gz"
          tar -czf "$result" "$dirname"
          sha256sum "$result" > "$result.sha256"
          echo "RESULT=$result" | tee --append $GITHUB_ENV
      # - name: Release
      #   uses: softprops/action-gh-release@v1
      #   with:
      #     files: |
      #       ${{ env.RESULT }}
      #       ${{ env.RESULT }}.sha256
